import { domains, profile } from '../content/profile';
import { projects } from '../content/projects';
import { ProjectCard } from '../components/case-study';
import { SectionHeading, SystemMap } from '../components/sections';

export default function Home() {
  return <main id="main" className="container">
    <section className="hero" aria-labelledby="hero-title">
      <div className="hero-copy"><p className="eyebrow"><span className="status-dot" aria-hidden="true"/> SASIRU VISHMIKA / ENGINEERING PORTFOLIO</p><h1 id="hero-title">Software.<br/>Cloud.<br/><span>Infrastructure.</span></h1><p className="hero-subtitle">Built with a systems mindset.</p><p className="hero-description">I’m Sasiru Vishmika, an engineer connecting software with cloud, DevOps, networking and security. From application logic to the infrastructure behind it.</p><div className="actions"><a className="button primary" href="#work">View engineering work <span aria-hidden="true">↗</span></a><a className="button" href={profile.github}>Explore GitHub <span aria-hidden="true">↗</span></a></div></div><SystemMap/>
      <div className="hero-foot"><span>SRI LANKA</span><span>SOFTWARE FOUNDATION → SYSTEMS THINKING</span><a href="#work">SCROLL TO EXPLORE <span aria-hidden="true">↓</span></a></div>
    </section>
    <section id="work" className="section"><SectionHeading index="01" eyebrow="Selected engineering work" title="The work behind the words.">Source-backed projects, architectural decisions and lessons—not just screenshots.</SectionHeading><div className="project-grid">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} index={index}/>)}</div></section>
    <section id="domains" className="section"><SectionHeading index="02" eyebrow="Engineering domains" title="Across the system.">My current technical direction spans six connected areas, grounded in a software engineering foundation.</SectionHeading><div className="domain-grid">{domains.map(d => <article className="domain-card" key={d.title}><span className="mono domain-number">{d.number}</span><h3>{d.title}</h3><p>{d.description}</p><p className="domain-preview">{d.tools.slice(0, 4).join(' / ')}</p></article>)}</div></section>
    <section id="about" className="section about-grid"><div><p className="eyebrow">03 / About</p><h2>Beyond the<br/><span className="muted">application layer.</span></h2></div><div className="reading"><p className="lead">My starting point is software engineering. My direction is the whole system.</p><p>I’m building on a Computer Science foundation to explore how applications are delivered, connected, operated and secured. Cloud infrastructure, deployment workflows and network boundaries are part of the same engineering conversation.</p><p>That perspective shapes how I approach technical work: understand the dependencies, make the trade-offs visible and keep learning from what breaks.</p><a className="text-link" href="#stack">See my technical toolkit <span aria-hidden="true">↗</span></a></div></section>
    <section id="background" className="section"><SectionHeading index="04" eyebrow="Experience & education" title="Foundation. Then forward."/><div className="timeline"><article><span className="mono">PROJECT PRACTICE</span><div><h3>Independent & academic engineering work</h3><p>Public repositories document software projects and an Azure deployment workflow. The case studies distinguish implementation evidence from areas of current focus.</p><a className="text-link" href="#work">Explore selected work <span aria-hidden="true">↗</span></a></div></article><article><span className="mono">EDUCATION</span><div><h3>Computer Science degree</h3><p>A foundation in software, data and problem-solving that supports my progression toward cloud, infrastructure and security engineering.</p></div></article><article><span className="mono">CURRENT DIRECTION</span><div><h3>Cloud, platforms & secure infrastructure</h3><p>Developing an end-to-end engineering perspective across delivery, networking, systems operations and security fundamentals.</p></div></article></div></section>
    <section id="stack" className="section"><SectionHeading index="05" eyebrow="Technical stack" title="A toolkit, not a scorecard.">Technologies and concepts from my current technical profile. Scope varies by area; project pages show what the source supports.</SectionHeading><div className="stack-grid">{domains.map(d => <div className="stack-group" key={d.title}><h3>{d.title}</h3><ul className="tags">{d.tools.map(t => <li key={t}>{t}</li>)}</ul></div>)}</div></section>
    <section id="contact" className="section contact"><p className="eyebrow">06 / Let’s connect</p><h2>Good systems start<br/>with a conversation.</h2><p>For engineering opportunities, technical conversations or collaboration.</p><a className="contact-email" href={`mailto:${profile.email}`}>{profile.email} <span aria-hidden="true">↗</span></a><div className="actions"><a className="button" href={profile.github}>GitHub <span aria-hidden="true">↗</span></a><a className="button" href={profile.linkedin}>LinkedIn <span aria-hidden="true">↗</span></a><a className="text-link" href={`mailto:${profile.email}?subject=Resume%20request`}>Request my resume <span aria-hidden="true">↗</span></a></div><div className="github-note"><span className="mono">PUBLIC ENGINEERING ACTIVITY</span><p>Browse the repositories, history and source on GitHub. No synthetic activity counters.</p></div></section>
  </main>;
}
