export const domains = [
  { title: 'Cloud & infrastructure', number: '01', description: 'The foundations beneath the application: compute, connectivity and identity.', tools: ['Azure', 'AWS', 'Google Cloud', 'AKS', 'Virtual machines', 'VNets / VPCs', 'Load balancers', 'Private endpoints / Private Link', 'DNS / Private DNS', 'Key Vault', 'Cloud architecture'] },
  { title: 'DevOps & platform', number: '02', description: 'From a source change to a repeatable deployment, with operations in mind.', tools: ['Docker', 'Kubernetes', 'Helm', 'CI/CD', 'GitHub', 'Bitbucket', 'Self-hosted CI runners', 'Deployment automation', 'Linux administration', 'Windows Server / IIS', 'Observability concepts', 'Production troubleshooting'] },
  { title: 'Networking', number: '03', description: 'Understanding how systems communicate—and where that communication breaks.', tools: ['TCP/IP', 'OSI model', 'IPv4', 'Subnetting', 'Routing', 'Switching', 'VLAN concepts', 'DNS', 'DHCP', 'NAT', 'Firewalls', 'Cloud networking', 'Network troubleshooting'] },
  { title: 'Security', number: '04', description: 'Identity, secrets and network boundaries as part of system design.', tools: ['Network security', 'Cloud security', 'IAM concepts', 'Secrets management', 'Private network architecture', 'Vulnerability fundamentals', 'Secure infrastructure design', 'DevSecOps concepts', 'Cybersecurity fundamentals'] },
  { title: 'Software engineering', number: '05', description: 'A software foundation that connects application behavior to the systems running it.', tools: ['.NET / C#', 'Python', 'FastAPI', 'JavaScript / TypeScript', 'Next.js / React', 'Flutter / Dart', 'REST APIs', 'SQL', 'Git'] },
  { title: 'Data & AI', number: '06', description: 'Exploring data-driven applications alongside practical automation.', tools: ['Python automation', 'AI / ML project work', 'Data / cloud automation'] },
] as const;
export const profile = { name: 'Sasiru Vishmika', email: 'sasiruvishmika@gmail.com', github: 'https://github.com/Sasiru382', linkedin: 'https://www.linkedin.com/in/sasiru-vishmika' } as const;
